const test = require('node:test');
const assert = require('node:assert/strict');
const { JSDOM } = require('jsdom');
const fs = require('fs/promises');

// A placeholder for the actual TOC generation logic (if it's client-side)
// For server-side rendering, we assume the HTML comes with TOC already.
// For now, we'll simulate a basic ID generation and TOC creation for testing purposes
function applyTocLogic(document) {
    const postContent = document.querySelector('.post-content');
    if (!postContent) return;

    const headings = postContent.querySelectorAll('h2, h3');
    const tocList = document.createElement('ul');
    tocList.className = 'toc-list';

    let currentH2Item = null;

    headings.forEach((heading, index) => {
        const textContent = heading.textContent.trim();
        const slug = textContent.replace(/[^a-zA-Z0-9\u4e00-\u9fa5\s-]/g, '') // Remove special chars
                                  .replace(/\s+/g, '-') // Replace spaces with hyphens
                                  .toLowerCase();
        const id = `${slug}-${index}`;
        heading.setAttribute('id', id);

        const listItem = document.createElement('li');
        const link = document.createElement('a');
        link.href = `#${id}`;
        link.textContent = textContent;
        listItem.appendChild(link);

        if (heading.tagName === 'H2') {
            listItem.className = 'toc-nav-level-2';
            tocList.appendChild(listItem);
            currentH2Item = listItem;
        } else if (heading.tagName === 'H3') {
            listItem.className = 'toc-nav-level-3';
            if (currentH2Item) {
                let subList = currentH2Item.querySelector('ul');
                if (!subList) {
                    subList = document.createElement('ul');
                    currentH2Item.appendChild(subList);
                }
                subList.appendChild(listItem);
            } else {
                // If an H3 appears before any H2, append to main list (or handle as error)
                tocList.appendChild(listItem);
            }
        }
    });

    const tocContainer = document.querySelector('.toc-nav');
    if (tocContainer && tocList.children.length > 0) {
        tocContainer.appendChild(tocList);
    }
}

test('Feature: Article page auto TOC and anchor navigation (H2/H3 only)', async (t) => {
    let htmlContent = await fs.readFile('tmp/test-post-with-headings.html', 'utf-8');

    const dom = new JSDOM(htmlContent, {
        url: 'https://example.com/test-post/',
    });
    const { document } = dom.window;

    // Simulate the JS logic that would run on the client or server to generate TOC
    applyTocLogic(document);

    const tocContainer = document.querySelector('.toc-nav');
    assert.ok(tocContainer, 'AC1: Expected a TOC container element to be present');

    const h1 = document.querySelector('h1');
    const h2_1 = document.querySelector('h2:nth-of-type(1)');
    const h3_1 = document.querySelector('h3:nth-of-type(1)');
    const h4 = document.querySelector('h4');
    const h2_2 = document.querySelector('h2:nth-of-type(2)');
    const h3_2 = document.querySelector('h3:nth-of-type(2)');
    const h3_3 = document.querySelector('h3:nth-of-type(3)'); // H3 with special chars

    // AC4: Assert heading IDs are generated for H2/H3
    assert.ok(h2_1.id, 'AC4: Expected first h2 to have an ID');
    assert.ok(h3_1.id, 'AC4: Expected first h3 to have an ID');
    assert.ok(h2_2.id, 'AC4: Expected second h2 to have an ID');
    assert.ok(h3_2.id, 'AC4: Expected second h3 to have an ID');
    assert.ok(h3_3.id, 'AC4: Expected special char h3 to have an ID');

    // Verify H1 and H4 do NOT have IDs generated by our logic (if this was part of a larger ID generation, it might have one, but our specific logic skips it)
    // This assertion should pass if our `applyTocLogic` is correctly implemented.
    assert.ok(!h1.id.startsWith('main-article-title'), 'Boundary: H1 should not have an ID from our TOC logic.');
    assert.ok(!h4.id.startsWith('细节1'), 'Boundary: H4 should not have an ID from our TOC logic.');


    const tocLinks = Array.from(tocContainer.querySelectorAll('a[href^="#"]'));
    // Expected TOC links: two H2s, three H3s = 5 links
    assert.equal(tocLinks.length, 5, 'AC1: Expected 5 TOC links (2 H2s, 3 H3s)');

    // AC2: Link correctness and AC6: Special character support
    assert.equal(tocLinks[0].textContent.trim(), '第一节：主要概念', 'AC2: First H2 TOC text correct');
    assert.equal(tocLinks[0].getAttribute('href'), `#${h2_1.id}`, 'AC2: First H2 TOC href correct');

    assert.equal(tocLinks[1].textContent.trim(), '1.1 子主题A', 'AC2: First H3 TOC text correct');
    assert.equal(tocLinks[1].getAttribute('href'), `#${h3_1.id}`, 'AC2: First H3 TOC href correct');

    assert.equal(tocLinks[2].textContent.trim(), '第二节：进阶内容', 'AC2: Second H2 TOC text correct');
    assert.equal(tocLinks[2].getAttribute('href'), `#${h2_2.id}`, 'AC2: Second H2 TOC href correct');

    assert.equal(tocLinks[3].textContent.trim(), '2.1 子主题B', 'AC2: Second H3 TOC text correct');
    assert.equal(tocLinks[3].getAttribute('href'), `#${h3_2.id}`, 'AC2: Second H3 TOC href correct');
    
    assert.equal(tocLinks[4].textContent.trim(), '2.2 子主题C - 带有特殊字符 & 符号', 'AC6: Special char H3 TOC text correct');
    assert.equal(tocLinks[4].getAttribute('href'), `#${h3_3.id}`, 'AC6: Special char H3 TOC href correct');

    // AC3: Smooth scrolling (cannot be directly tested with JSDOM, will be a manual check or integration test)

    // AC5: Hierarchy check (H3 under H2)
    const firstH2TocItem = tocContainer.querySelector(`li.toc-nav-level-2 > a[href="#${h2_1.id}"]`).parentNode;
    assert.ok(firstH2TocItem, 'AC5: Expected first H2 TOC item');
    const firstH3TocItem = firstH2TocItem.querySelector(`ul > li.toc-nav-level-3 > a[href="#${h3_1.id}"]`).parentNode;
    assert.ok(firstH3TocItem, 'AC5: Expected first H3 nested under first H2');

    const secondH2TocItem = tocContainer.querySelector(`li.toc-nav-level-2 > a[href="#${h2_2.id}"]`).parentNode;
    assert.ok(secondH2TocItem, 'AC5: Expected second H2 TOC item');
    const secondH3TocItem = secondH2TocItem.querySelector(`ul > li.toc-nav-level-3 > a[href="#${h3_2.id}"]`).parentNode;
    assert.ok(secondH3TocItem, 'AC5: Expected second H3 nested under second H2');
    const thirdH3TocItem = secondH2TocItem.querySelector(`ul > li.toc-nav-level-3 > a[href="#${h3_3.id}"]`).parentNode;
    assert.ok(thirdH3TocItem, 'AC5: Expected third H3 nested under second H2');

    // Check that H1 and H4 are NOT in the TOC
    assert.equal(tocContainer.querySelector('a[href^="#main-article-title"]'), null, 'Boundary: H1 should not be in TOC');
    assert.equal(tocContainer.querySelector('a[href^="#细节1"]'), null, 'Boundary: H4 should not be in TOC');

});

// AC7: Test case for no H2/H3 headings (no TOC generated)
test('AC7: No TOC generated if no H2/H3 headings present', async (t) => {
    const noHeadingsHtml = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test Post without Headings</title>
</head>
<body>
    <article class="post-content">
        <h1>Main Title</h1>
        <p>This is a post without H2 or H3 headings.</p>
    </article>
    <div class="toc-nav"></div>
</body>
</html>`;

    const dom = new JSDOM(noHeadingsHtml);
    const { document } = dom.window;

    applyTocLogic(document);

    const tocContainer = document.querySelector('.toc-nav');
    assert.ok(tocContainer, 'Expected TOC container to be present'); // The container itself can exist
    assert.equal(tocContainer.children.length, 0, 'AC7: Expected TOC container to be empty'); // But it should have no children (no TOC list)
    assert.equal(tocContainer.querySelector('ul'), null, 'AC7: Expected no ul element within TOC container');
});
