const { JSDOM } = require('jsdom');
const TocScrollSpyFactory = require('../themes/evan/source/js/toc-scrollspy'); // Import the factory

function setupDom(html) {
  const dom = new JSDOM(`<!doctype html><html><body><nav class="toc-nav"></nav><article class="article-content">${html}</article></body></html>`, {
    url: 'https://example.com/posts/test-post/' // Provide a URL for location.href
  });
  const TocScrollSpy = TocScrollSpyFactory(dom.window.document, dom.window);
  TocScrollSpy.initTocScrollSpy({
    headingSelector: 'h1, h2, h3' // Explicitly include H1 for this test
  }); // Initialize after DOM setup
  return dom;
}

describe('Heading IDs for TOC and Anchors', () => {
  test('H1, H2, and H3 headings in article content should have unique IDs', () => {
    const dom = setupDom(`
      <h1>Main Title</h1>
      <p>Some content.</p>
      <h2>Section 1</h2>
      <p>More content.</p>
      <h3>Subsection 1.1</h3>
      <p>Even more content.</p>
      <h2>Section 2</h2>
      <h3>Subsection 2.1</h3>
      <h1>Another Main Title</h1>
    `);

    const { document } = dom.window;
    const headings = Array.from(document.querySelectorAll('.article-content h1, .article-content h2, .article-content h3'));

    headings.forEach(heading => {
      expect(heading.id).toBeDefined();
      expect(heading.id).not.toBe('');
    });

    const ids = headings.map(heading => heading.id);
    const uniqueIds = new Set(ids);
    expect(ids.length).toBe(uniqueIds.size);
  });

  function generateTocLinks(document) {
    const headings = Array.from(document.querySelectorAll('.article-content h1, .article-content h2, .article-content h3'));
    return headings.map(heading => {
      if (heading.id) {
        return { text: heading.textContent, href: `#${heading.id}` };
      }
      return null;
    }).filter(Boolean);
  }

  test('Generated TOC links should point to existing heading IDs', () => {
    // The setupDom now calls initTocScrollSpy, which runs ensureHeadingIds
    const dom = setupDom(`
      <h1>Main Title</h1>
      <h2>Section 1</h2>
      <h3>Subsection 1.1</h3>
    `);

    const { document } = dom.window;

    const tocLinks = generateTocLinks(document);
    expect(tocLinks.length).toBe(3);

    // Expecting IDs to be generated by ensureHeadingIds
    const h1Id = document.querySelector('h1').id;
    const h2Id = document.querySelector('h2').id;
    const h3Id = document.querySelector('h3').id;

    expect(tocLinks[0].href).toBe(`#${h1Id}`);
    expect(tocLinks[1].href).toBe(`#${h2Id}`);
    expect(tocLinks[2].href).toBe(`#${h3Id}`);

    tocLinks.forEach(link => {
      const targetElement = document.querySelector(link.href);
      expect(targetElement).not.toBeNull();
      // Ensure the text content also matches, as IDs might be slugified
      expect(targetElement.textContent).toBe(link.text);
    });
  });
});
